language: python
python:
  - "3.8"
os: linux

env:
  global:
  - PGVER=12
  - PGPORT=5433
  - PGUSER=travis
  # - PGPASSWORD=pollspassword123

services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
      - postgresql-client-common
      - postgresql-common

before_install:
  - sudo sed -i -e "/local.*peer/s/postgres/all/" -e "s/peer\|md5/trust/g" /etc/postgresql/*/main/pg_hba.conf
  - postgres --version
  - sudo pg_ctlcluster 12 main restart
  # - "if [ ! -z $PGVER ]; then sudo cp /etc/postgresql/{9.6,$PGVER}/main/pg_hba.conf; fi"
  # - "if [ ! -z $PGVER ]; then sudo service postgresql restart $PGVER; fi"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - psql -c 'create database djangopolls;' -U travis
  - python manage.py migrate
  # - python manage.py collectstatic --noinput


script:
  - black --check . --skip-string-normalization --exclude settings* --extend-exclude migrations*
  - flake8 .
  - coverage run --source=polls manage.py test


after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_APP_NAME
  env: $AWS_ENV_NAME
  bucket_name: $AWS_BUCKET_NAME
  on:
    branch: main

after_deploy:
  - ./scripts/after_deploy_1.sh