language: python
python:
  - "3.8"
os: linux

env:
  global:
  - PGPORT=5432
  - PGUSER=djangopollsuser
  - PGPASSWORD=pollspassword123

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - psql -c 'create database django-polls;' -U djangopollsuser
  - python manage.py migrate
  - python manage.py collectstatic --noinput


script:
  - black --check .
  - flake8 .
  - coverage run --source=polls manage.py test


after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_APP_NAME
  env: $AWS_ENV_NAME
  bucket_name: $AWS_BUCKET_NAME

after_deploy:
  - ./scripts/after_deploy_1.sh